version: '3.8'
services:
  train:
    build: .
    gpus: all
    volumes:
      - .:/app
    command: python main.py

  predict:
    build: .
    gpus: all
    volumes:
      - .:/app
    command: python predict_with_model.py
